"use client";
import { FormEvent, useEffect, useState } from "react";
import { getAuth } from "@/lib/auth-client";
type Review = { id: string; score: number; suggestions: string; improvedResumeText: string | null };
export default function ResumeCheckerPage() { const [resumeText, setResumeText] = useState(""); const [reviews, setReviews] = useState<Review[]>([]); const [loading, setLoading] = useState(false);
const load = async () => { const auth = getAuth(); if (!auth) return; const res = await fetch("/api/resume-checker", { headers: { Authorization: `Bearer ${auth.token}` } }); const data = await res.json(); if (data.success) setReviews(data.data); };
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(() => { void load(); }, []);
const submit = async (e: FormEvent) => { e.preventDefault(); const auth = getAuth(); if (!auth) return; setLoading(true); await fetch("/api/resume-checker", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${auth.token}` }, body: JSON.stringify({ resumeText }) }); setLoading(false); setResumeText(""); void load(); };
const improve = async (reviewId: string) => { const auth = getAuth(); if (!auth) return; await fetch("/api/resume-checker", { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${auth.token}` }, body: JSON.stringify({ reviewId }) }); void load(); };
return <div className="max-w-5xl mx-auto space-y-6"><h1 className="text-3xl font-bold">Resume Checker</h1><form onSubmit={submit} className="space-y-3"><textarea className="w-full min-h-48 rounded-xl border p-3" value={resumeText} onChange={(e)=>setResumeText(e.target.value)} placeholder="Paste your resume here" required /><button className="rounded-lg bg-blue-600 text-white px-4 py-2" disabled={loading}>{loading ? "Analyzing..." : "Analyze Resume"}</button></form><div className="grid gap-4 md:grid-cols-2">{reviews.map((r)=><div key={r.id} className="rounded-xl border p-4 bg-white dark:bg-zinc-900"><p className="font-semibold">Score: {r.score}/100</p><p className="text-sm whitespace-pre-wrap mt-2">{r.suggestions}</p>{r.improvedResumeText && <details className="mt-2"><summary className="cursor-pointer">AI Improved Resume</summary><pre className="text-xs whitespace-pre-wrap mt-2">{r.improvedResumeText}</pre></details>}<button className="mt-3 rounded-md border px-3 py-1 text-sm" onClick={()=>improve(r.id)}>Update with AI</button></div>)}</div></div>; }
